GET http://localhost:3001/api/v1/users

###

POST http://localhost:3001/api/v1/users
Content-Type: application/json

{
    "username": "mishevski-k",
    "name": "Kiril Mishevski",
    "password": "sudo"
}