GET http://localhost:3001/

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/v1/persons

###

GET http://localhost:3001/api/v1/persons/1

###

DELETE http://localhost:3001/api/v1/persons/1